<?php
/**
 * @file
 * ticket_sales.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function ticket_sales_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_buy_tickets'
  $field_bases['field_buy_tickets'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_buy_tickets',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'commerce_tickets',
    'settings' => array(
      'buttun_text' => 'Buy Now',
      'collect_name' => 0,
      'no_of_tickets' => 5,
    ),
    'translatable' => 0,
    'type' => 'commerce_tickets_field',
  );

  // Exported field_base: 'field_event'
  $field_bases['field_event'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_event',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'base',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 0,
          ),
        ),
        'sort' => array(
          'type' => 'none',
        ),
        'target_bundles' => array(
          'event' => 'event',
        ),
      ),
      'target_type' => 'node',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  // Exported field_base: 'field_track_tickets_for_this_eve'
  $field_bases['field_track_tickets_for_this_eve'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_track_tickets_for_this_eve',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => '',
        1 => '',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  return $field_bases;
}
